aws_access_key = "AKIAQCO22FFC5N32K2V3"
aws_secret_key = "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"
aws_region = "us-east-1"
vpc_cidr = "10.1.0.0/16"
public_subnet1_cidr = "10.1.1.0/24"
public_subnet2_cidr = "10.1.2.0/24"
public_subnet3_cidr = "10.1.3.0/24"
private_subnet_cidr = "10.1.20.0/24"
vpc_name = "TERRAFORM-TEST"
IGW_name = "TERRAFORM-TEST-IGW"
public_subnet1_name = "TERRAFORM-TEST_public_Subnet1-testing"
public_subnet2_name = "TERRAFORM-TEST_public_Subnet2-testing"
public_subnet3_name = "TERRAFORM-TEST_public_Subnet3-testing"
private_subnet_name = "TERRAFORM-TEST_private_Subnet-testing"
Main_Routing_Table = "TERRAFORM-TEST_Main_table-testing"
key_name = "devopskey"

